// Static demo data — used until backend provides real parsed data
export const STATIC_GRAPH_DATA = {
  nodes: [
    { id: "src/index.ts", group: 1, size: 8 },
    { id: "src/App.tsx", group: 2, size: 12 },
    { id: "src/components/Hero.tsx", group: 2, size: 7 },
    { id: "src/components/Galaxy.tsx", group: 2, size: 10 },
    { id: "src/lib/api.ts", group: 3, size: 5 },
    { id: "src/lib/utils.ts", group: 3, size: 4 },
    { id: "src/hooks/useGraph.ts", group: 4, size: 6 },
    { id: "src/styles/globals.css", group: 5, size: 3 },
    { id: "package.json", group: 5, size: 2 },
    { id: "README.md", group: 5, size: 1 },
    { id: "src/components/Chat.tsx", group: 2, size: 9 },
    { id: "src/components/DetailCard.tsx", group: 2, size: 8 },
    { id: "src/hooks/useLLM.ts", group: 4, size: 5 },
    { id: "src/types/index.ts", group: 3, size: 3 },
    { id: "src/context/RepoContext.tsx", group: 4, size: 4 },
  ],
  links: [
    { source: "src/index.ts", target: "src/App.tsx", type: "import" },
    { source: "src/App.tsx", target: "src/components/Hero.tsx", type: "import" },
    { source: "src/App.tsx", target: "src/components/Galaxy.tsx", type: "import" },
    { source: "src/App.tsx", target: "src/components/Chat.tsx", type: "import" },
    { source: "src/App.tsx", target: "src/components/DetailCard.tsx", type: "import" },
    { source: "src/components/Galaxy.tsx", target: "src/lib/api.ts", type: "import" },
    { source: "src/components/Galaxy.tsx", target: "src/hooks/useGraph.ts", type: "import" },
    { source: "src/components/Chat.tsx", target: "src/hooks/useLLM.ts", type: "import" },
    { source: "src/components/Chat.tsx", target: "src/lib/api.ts", type: "import" },
    { source: "src/components/DetailCard.tsx", target: "src/lib/api.ts", type: "import" },
    { source: "src/components/Hero.tsx", target: "src/lib/utils.ts", type: "import" },
    { source: "src/lib/api.ts", target: "src/types/index.ts", type: "import" },
    { source: "src/hooks/useGraph.ts", target: "src/context/RepoContext.tsx", type: "import" },
    { source: "src/context/RepoContext.tsx", target: "src/types/index.ts", type: "import" },
    { source: "src/components/Galaxy.tsx", target: "src/context/RepoContext.tsx", type: "import" },
    { source: "src/index.ts", target: "src/styles/globals.css", type: "link" },
  ],
};
